# just manual: https://github.com/casey/just#readme

_default:
    just --list

# Install dependencies only (for dev/test/ci)
bootstrap default="3.13":
    uv venv --python {{default}}
    just sync

# Sync dependencies with environment
sync:
    uv sync

# Update the lock file
lock:
    uv lock

# Update all dependencies to latest allowed versions
update:
    just sync

check:
    uv run ruff check .

fmt:
    uv run ruff format .

# Run all tests locally
test *args:
    #!/bin/bash -eux
    uv run pytest {{args}}